version: "3.9"

services:
  alert-monitor:
    build: .
    container_name: alert-monitor
    env_file:
      - .env
    volumes:
      - ./app/logs:/app/app/logs
      - ./state.json:/app/state.json
    restart: unless-stopped

  test-service:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: test-service
    ports:
      - "9090:9090"
    restart: unless-stopped
